openapi: 3.1.0
info:
  title: API Documentation
  version: 1.0.0
  description: API para la gestión de productos.
tags:
  - name: Products
    description: Operaciones relacionadas con productos.
paths:
  /api/products:
    get:
      tags:
        - Products
      summary: Obtener todos los productos
      description: Devuelve una lista de todos los productos.
      responses:
        '200':
          description: Lista de productos.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'

    post:
      tags:
        - Products
      summary: Crear un nuevo producto
      description: Crea un nuevo producto en el sistema.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: Producto creado exitosamente.
        '400':
          description: Datos incorrectos.

  /api/products/{pid}:
    get:
      tags:
        - Products
      summary: Obtener producto por ID
      description: Devuelve un producto específico por su ID.
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto
          schema:
            type: string
      responses:
        '200':
          description: Producto encontrado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Producto no encontrado.

    put:
      tags:
        - Products
      summary: Actualizar producto
      description: Actualiza un producto con el ID especificado.
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: Producto actualizado correctamente.
        '404':
          description: Producto no encontrado.

    delete:
      tags:
        - Products
      summary: Eliminar producto
      description: Elimina un producto con el ID especificado.
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto
          schema:
            type: string
      responses:
        '200':
          description: Producto eliminado correctamente.
        '404':
          description: Producto no encontrado.
