openapi: 3.1.0
info:
  title: API Documentation
  version: 1.0.0
  description: API para la gestión de carritos de compras.
tags:
  - name: Carts
    description: Operaciones relacionadas con los carritos de compras.
paths:
  /api/carts:
    get:
      tags:
        - Carts
      summary: Obtener todos los carritos
      description: Devuelve una lista de todos los carritos de compras.
      responses:
        '200':
          description: Lista de carritos.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cart'

    post:
      tags:
        - Carts
      summary: Crear un carrito
      description: Crea un nuevo carrito de compras.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                User:
                  type: string
                  description: ID del usuario para el carrito
                products:
                  type: array
                  items:
                    type: object
                    properties:
                      product:
                        type: string
                        description: ID del producto
                      quantity:
                        type: integer
                        description: Cantidad del producto
      responses:
        '201':
          description: Carrito creado exitosamente.
        '400':
          description: Datos incorrectos.

  /api/carts/{cid}:
    get:
      tags:
        - Carts
      summary: Obtener carrito por ID
      description: Devuelve el carrito de compras con el ID especificado.
      parameters:
        - name: cid
          in: path
          required: true
          description: ID del carrito
          schema:
            type: string
      responses:
        '200':
          description: Carrito encontrado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        '404':
          description: Carrito no encontrado.

    post:
      tags:
        - Carts
      summary: Actualizar carrito por ID
      description: Actualiza el contenido del carrito con el ID especificado.
      parameters:
        - name: cid
          in: path
          required: true
          description: ID del carrito
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                products:
                  type: array
                  items:
                    type: object
                    properties:
                      product:
                        type: string
                        description: ID del producto
                      quantity:
                        type: integer
                        description: Cantidad del producto
      responses:
        '200':
          description: Carrito actualizado correctamente.
        '400':
          description: Datos incorrectos.
        '404':
          description: Carrito no encontrado.

  /api/carts/{cid}/purchase:
    get:
      tags:
        - Carts
      summary: Verificar carrito para la compra
      description: Muestra la vista de compra para el carrito especificado.
      parameters:
        - name: cid
          in: path
          required: true
          description: ID del carrito
          schema:
            type: string
      responses:
        '200':
          description: Vista de compra mostrada.
        '404':
          description: Carrito no encontrado.

    post:
      tags:
        - Carts
      summary: Procesar compra
      description: Realiza el proceso de compra para el carrito con el ID especificado.
      parameters:
        - name: cid
          in: path
          required: true
          description: ID del carrito
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                purchaser:
                  type: string
                  description: Nombre del comprador
                fullName:
                  type: string
                  description: Nombre completo
                adress:
                  type: string
                  description: Dirección de envío
      responses:
        '200':
          description: Compra procesada correctamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ticket'
        '400':
          description: Datos incorrectos.
        '404':
          description: Carrito no encontrado.

  /api/carts/{cid}/product/{pid}:
    post:
      tags:
        - Carts
      summary: Agregar producto al carrito
      description: Agrega un producto al carrito con el ID especificado.
      parameters:
        - name: cid
          in: path
          required: true
          description: ID del carrito
          schema:
            type: string
        - name: pid
          in: path
          required: true
          description: ID del producto
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
                  description: Cantidad del producto a agregar
      responses:
        '200':
          description: Producto agregado exitosamente.
        '404':
          description: Carrito o producto no encontrado.

    put:
      tags:
        - Carts
      summary: Actualizar cantidad de producto en el carrito
      description: Actualiza la cantidad de un producto en el carrito con el ID especificado.
      parameters:
        - name: cid
          in: path
          required: true
          description: ID del carrito
          schema:
            type: string
        - name: pid
          in: path
          required: true
          description: ID del producto
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
                  description: Nueva cantidad del producto
      responses:
        '200':
          description: Cantidad actualizada exitosamente.
        '404':
          description: Carrito o producto no encontrado.

    delete:
      tags:
        - Carts
      summary: Eliminar producto del carrito
      description: Elimina un producto del carrito con el ID especificado.
      parameters:
        - name: cid
          in: path
          required: true
          description: ID del carrito
          schema:
            type: string
        - name: pid
          in: path
          required: true
          description: ID del producto
          schema:
            type: string
      responses:
        '200':
          description: Producto eliminado correctamente.
        '404':
          description: Carrito o producto no encontrado.

  /api/carts/{cid}/product/{pid}/delete:
    delete:
      tags:
        - Carts
      summary: Eliminar todos los productos del carrito
      description: Elimina todos los productos del carrito con el ID especificado.
      parameters:
        - name: cid
          in: path
          required: true
          description: ID del carrito
          schema:
            type: string
      responses:
        '200':
          description: Carrito vacío correctamente.
        '404':
          description: Carrito no encontrado.

components:
  schemas:
    Cart:
      type: object
      properties:
        _id:
          type: string
          description: ID del carrito
        User:
          type: string
          description: ID del usuario asociado
        products:
          type: array
          items:
            type: object
            properties:
              product:
                type: string
                description: ID del producto
              quantity:
                type: integer
                description: Cantidad del producto
      required:
        - _id
        - User

    Ticket:
      type: object
      properties:
        code:
          type: string
        purchaser:
          type: string
        fullName:
          type: string
        adress:
          type: string
        totalPrice:
          type: number
        date:
          type: string
          format: date-time
        products:
          type: array
          items:
            type: object
            properties:
              productId:
                type: string
                description: ID del producto
              product:
                type: string
              quantity:
                type: integer
              price:
                type: number
      required:
        - code
        - purchaser
        - fullName
        - adress
        - totalPrice
        - products
